AWSTemplateFormatVersion: 2010-09-09
Description: A VPC Template For Flipkart VPC - CloudFormation template with YAML comments.
# Resources section
Resources:
  flipkartVPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: flipkart 

  flipkartPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref flipkartVPC
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: flipkart-public-subnet

  flipkartPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref flipkartVPC
      CidrBlock: 10.0.1.0/24
      Tags:
      - Key: Name
        Value: flipkart-private-subnet

  flipkartInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: flipkart-igw 

  flipkartAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: flipkartVPC
      InternetGatewayId:
        Ref: flipkartInternetGateway
  